FROM python:3.12-alpine
WORKDIR /app
COPY api/requirements.txt .
RUN pip install --no-cache-dir -r api/requirements.txt
COPY api/ .
EXPOSE 8000
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
