FROM python:3.12-alpine
WORKDIR /app
RUN apk add --no-cache gcc musl-dev
COPY requirements.txt .
RUN pip install --no-cache-dir redis
COPY master_server.py .
EXPOSE 27011/udp
CMD ["python", "master_server.py"]
